---
title: "Lobster Report"
author: "Kathryn Tomasi"
format: html
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
#| warning: false
#| message: false
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
```

```{r}
#| warning: false
#| message: false
lobster_abundance <- read_csv("data/Lobster_Abundance_All_Years_20220829.csv")
```

Exploring the data

```{r}
colnames(lobster_abundance)

str(lobster_abundance)

head(lobster_abundance)

unique(lobster_abundance$SITE)

summary(lobster_abundance)
```

```{r}
lobster_abundance <- lobster_abundance %>% 
  mutate(SIZE_MM = na_if(SIZE_MM, -99999))

unique(lobster_abundance$SIZE_MM)
```



```{r}
not_napl <- lobster_abundance %>% 
  filter(SITE != "NAPL")

unique(not_napl$SITE)
```

```{r}
aque_70mm <- lobster_abundance %>% 
  filter(SITE == "AQUE",
         SIZE_MM >= 70)
```

## Exercise: Data Visualization

```{r}
fig2 <- ggplot(data = lobster_abundance, aes(x = SIZE_MM)) +
    geom_histogram() +
    facet_wrap(~SITE) #~ will access variable in the df

fig2
```

```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())
```


```{r}
fig3 <- ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE)) +
  geom_line(aes(color = SITE)) 

fig3
```


```{r}
lobster_size_lrg <- lobster_abundance %>% 
    filter(YEAR %in% c(2019, 2020, 2021)) %>% 
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>% 
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()

```

```{r}
# bar plot
ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
    geom_col()

# dodged bar plot
fig4 <- ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
    geom_col(position = "dodge")

fig4
```

```{r}
ggsave("figs/figs2.png")
```

